version: "2.1"

services:
    cms-db:
        image: mysql:5.6
        volumes:
            - "/var/lib/mysql:Z"
        environment:
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        mem_limit: 1g
        env_file: config.env
        restart: always
    cms-xmr:
        image: xibosignage/xibo-xmr:release-0.8
        ports:
            - "9505:9505"
        restart: always
        mem_limit: 256m
        env_file: config.env
    cms-web:
        image: xibosignage/xibo-cms:release-2.3.6
        volumes:
            - "/var/www/cms/custom:Z"
            - "/var/www/backup:Z"
            - "/var/www/cms/web/theme/custom:Z"
            - "/var/www/cms/library:Z"
            - "/var/www/cms/web/userscripts:Z"
            - "/var/www/cms/ca-certs:Z"
        restart: always
        links:
            - cms-db:mysql
            - cms-xmr:50001
        environment:
            - XMR_HOST=cms-xmr
        env_file: config.env
        ports:
            - "80:80"
        mem_limit: 1g
    cms-quickchart:
      image: ianw/quickchart
      restart: always
